name: Build example project
on: [pull_request, push]
jobs:
  build_native:
    strategy:
      fail-fast: false
      matrix:
        include:
        - { name: "windows - bzlmod native", os: windows-latest, command: "build",  config: "--enable_bzlmod", bazel_options: "--output_user_root=C:\\bazelroot", }
        - { name: "ubuntu  - bzlmod native", os: ubuntu-latest,  command: "build",  config: "--enable_bzlmod", bazel_options: "",                                 }
        - { name: "macos   - bzlmod native", os: macos-latest,   command: "build",  config: "--enable_bzlmod", bazel_options: "",                                 }

    name: "Build - ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: bazel ${{ matrix.bazel_options }} build -k ${{ matrix.config }} --verbose_failures --enable_bzlmod //...
